'use client';

import { Link, useParams } from 'react-router-dom'
import { useState } from 'react'
import { addComment, completeTask, getSession, taskFixtures } from '@/lib/api'
import '@/styles/Dashboard.css'

export default function TaskDetail() {
  const { id } = useParams()
  const task = taskFixtures.find((item) => item.id === id) || taskFixtures[0]
  const [comments, setComments] = useState([{ author: 'Sarah Johnson', text: 'The context is clear. I added the latest team numbers to the shared report.', avatar: '/kpily/avatar-01.png' }])
  const [comment, setComment] = useState<string>('')
  const [completed, setCompleted] = useState(task.status === 'Completed')
  async function submitComment(event) { event.preventDefault(); if (!comment.trim()) return; const saved = await addComment(getSession()?.token, { message: comment, taskID: task.id, parent: task.id }); setComments((current) => [...current, { author: 'Elias Akin', text: saved.message || comment, avatar: '/kpily/avatar-03.png' }]); setComment('') }
  async function markComplete() { await completeTask(getSession()?.token, task.id, task.reward); setCompleted(true) }
  return <div className="app-shell task-page"><DashboardShell active="/tasks"><main className="dashboard-content"><div className="welcome-row"><div><Link href='/tasks' className="text-link">← Back to tasks</Link><p className="eyebrow-dashboard" style={{ marginTop: 22 }}>Task detail</p><h2>{task.name}</h2><p>Review ownership, progress, KPI score, and feedback for this task.</p></div><button className="primary-action" onClick={markComplete} disabled={completed}>{completed ? '✓ Completed' : 'Mark complete'}</button></div><div className="task-detail-grid"><section className="surface detail-card"><h2>{task.name}</h2><p>{task.description}</p><div className="detail-meta"><Meta label="Status" value={completed ? 'Completed' : task.status} /><Meta label="Priority" value={task.priority} /><Meta label="KPI score" value={`${task.kpi}%`} /><Meta label="Goal" value={task.goal} /><Meta label="Reward" value={`${task.reward} XP`} /><Meta label="Due" value={task.dueDate} /></div><h3 style={{ fontSize: 15, color: '#173a44', marginTop: 30 }}>Comments & feedback</h3>{comments.map((item, index) => <div className="comment" key={index}><div className="assignee"><img src={item.avatar} alt="" /><div><strong>{item.author}</strong><span>Performance workspace</span></div></div><span>{item.text}</span></div>)}<form className="comment-box" onSubmit={submitComment}><input value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Leave a comment or feedback" aria-label="Comment" /><button className="primary-action" type="submit">Send</button></form></section><aside className="detail-side"><section className="surface detail-card"><h3 style={{ margin: 0, fontSize: 15, color: '#173a44' }}>Assigned teammate</h3><div className="assignee" style={{ marginTop: 18 }}><img src="/kpily/avatar-03.png" alt={task.assignee} /><div><strong>{task.assignee}</strong><span>Performance Lead</span></div></div></section><section className="surface detail-card"><h3 style={{ margin: 0, fontSize: 15, color: '#173a44' }}>Next step</h3><p style={{ marginBottom: 0 }}>Complete the remaining checks, then submit the task for review. Your final points will be awarded after completion.</p></section></aside></div></main></DashboardShell></div>
}
function Meta({ label, value }) { return <div className="detail-meta-item"><span>{label}</span><strong>{value}</strong></div> }
function DashboardShell({ active, children }) { return <DashboardLayout active={active}>{children}</DashboardLayout> }
function DashboardLayout({ active, children }) { return <div className="app-shell"><aside className="app-sidebar"><Link href='/'><img src="/assets/logo-full.png" alt="KPILY" className="app-logo" /></Link><p className="sidebar-label">Workspace</p><nav className="sidebar-nav">{[['⌂','Dashboard','/dashboard'],['◒','Performance','/performance'],['✓','Tasks','/tasks'],['▦','Projects','/projects'],['◉','Team','/team'],['◌','Chat','/chat'],['◷','Calendar','/calendar'],['◔','Notifications','/notifications']].map(([icon,label,path]) => <Link key={label} to={path} className={active === path ? 'active' : ''}><span className="sidebar-icon">{icon}</span>{label}</Link>)}</nav><p className="sidebar-label" style={{marginTop:28}}>Account</p><nav className="sidebar-nav"><Link href='/settings/profile'><span className="sidebar-icon">⚙</span>Settings</Link><Link href='/login'><span className="sidebar-icon">↪</span>Log out</Link></nav><div className="sidebar-bottom"><div className="profile-mini"><img src="/kpily/avatar-03.png" alt="Elias Akin" /><div><strong>Elias Akin</strong><span>Performance Lead</span></div></div></div></aside><div className="app-main"><header className="app-topbar"><div className="topbar-title"><div><h1>Tasks</h1><p>Workspace / Tasks</p></div></div><div className="topbar-actions"><label className="search-box">⌕<input placeholder="Search workspace" /></label><button className="top-icon">♢</button><img className="top-avatar" src="/kpily/avatar-03.png" alt="Elias Akin" /></div></header>{children}</div></div> }
