import { Link } from 'react-router-dom'
import { useMemo, useState } from 'react'
import { taskFixtures } from '../lib/api'
import './Dashboard.css'

const items = [['⌂','Dashboard','/dashboard'],['◒','Performance','/performance'],['✓','Tasks','/tasks'],['▦','Projects','/projects'],['◉','Team','/team'],['◌','Chat','/chat'],['◷','Calendar','/calendar'],['◔','Notifications','/notifications']]
function Frame({ children }) { return <div className="app-shell"><aside className="app-sidebar"><Link to="/"><img src="/assets/logo-full.png" alt="KPILY" className="app-logo" /></Link><p className="sidebar-label">Workspace</p><nav className="sidebar-nav">{items.map(([icon,label,path]) => <Link key={label} to={path} className={path === '/tasks' ? 'active' : ''}><span className="sidebar-icon">{icon}</span>{label}</Link>)}</nav><p className="sidebar-label" style={{ marginTop: 28 }}>Account</p><nav className="sidebar-nav"><Link to="/settings/profile"><span className="sidebar-icon">⚙</span>Settings</Link><Link to="/login"><span className="sidebar-icon">↪</span>Log out</Link></nav><div className="sidebar-bottom"><div className="profile-mini"><img src="/kpily/avatar-03.png" alt="Elias Akin" /><div><strong>Elias Akin</strong><span>Performance Lead</span></div></div></div></aside><div className="app-main"><header className="app-topbar"><div className="topbar-title"><h1>Tasks</h1><p>Workspace / Tasks</p></div><div className="topbar-actions"><label className="search-box">⌕<input placeholder="Search workspace" /></label><button className="top-icon" aria-label="Notifications">♢</button><img className="top-avatar" src="/kpily/avatar-03.png" alt="Elias Akin" /></div></header>{children}</div></div> }

export default function Tasks() {
  const [filter, setFilter] = useState('All')
  const filtered = useMemo(() => filter === 'All' ? taskFixtures : taskFixtures.filter((task) => task.status === filter), [filter])
  const columns = ['Assigned', 'In progress', 'Completed']
  return <Frame><main className="dashboard-content"><div className="welcome-row"><div><p className="eyebrow-dashboard">Task manager</p><h2>Tasks that move work forward.</h2><p>Track ownership, momentum, deadlines, and rewards in one place.</p></div><button className="primary-action">＋ Add new task</button></div><div className="task-toolbar"><label className="search-box">⌕<input placeholder="Search tasks" aria-label="Search tasks" /></label><select className="filter-select" value={filter} onChange={(event) => setFilter(event.target.value)}><option>All</option><option>Assigned</option><option>In progress</option><option>Completed</option></select></div><div className="task-board">{columns.map((column) => <section className="task-column" key={column}><h3>{column}<span>{filtered.filter((task) => task.status === column).length}</span></h3>{filtered.filter((task) => task.status === column).map((task) => <Link className="board-task" to={`/tasks/${task.id}`} key={task.id}><h4>{task.name}</h4><p>{task.description}</p><div className="board-task-footer"><span className={`priority ${task.priority.toLowerCase()}`}>{task.priority} priority</span><span>{task.dueDate}</span></div></Link>)}</section>)}</div></main></Frame>
}
